### ISSUE TITLE
questions on how it works

### ISSUE THREAD

**Issue by frankli0324** [trustedsec/ELFLoader#2]
sorry for asking a question in the issue section, but it seems that you didn't enable the `Discussions` section

I implemented something similar (idea wise) months before.

https://github.com/frankli0324/tinyld

I was struggling with making the dynamically linked libc functions to work, and I'm not sure I understand how you implemented this. Could you give me a hint on what did I do wrong?

with my implementation, I can only add something like

```c
else if (t_strcmp(symtab[symndx].st_name + strtab, "puts") == 0)
    *reloc_addr = (size_t)puts;
```

to somewhere near
https://github.com/frankli0324/tinyld/blob/10b85a75333a3f04a75dbb1c0650fb0c6742a578/dlopen.c#L166-L168

in order to get

```c
#include <stdio.h>
int execute(int argc, char **argv) {
    puts("test3\n");
    return 0;
}
// gcc -shared -fPIC -o test/libc.so test/libc.c -Wall -fPIC -g
```

to load and executed successfully

**Comment by kev169** [comment]
So that's sort of what I'm doing, the logic is in this function https://github.com/trustedsec/ELFLoader/blob/main/src/beacon_compatibility.c#L93 Essentially I check if the function is in my "mapping" array, and if it isn't then I do dlsym to get the address and return that. Then the calling function just sets the value.

**Comment by frankli0324** [comment]
oh... I see, thanks!
