### ISSUE TITLE
A SEGV crash leading to DEADLYSIGNAL was discovered

### ISSUE THREAD

**Issue by Asteriska001** [trustedsec/ELFLoader#7]
### Description
A SEGV crash was discovered in function ELFRunner src/ELFLoader.c:181
The issue is being triggered in function main src/ELFLoader.c:422

### Version
Version [34fd7ba](https://github.com/trustedsec/ELFLoader/commit/34fd7ba6ccc4368f87bcfc8e4ef702496e4c5655) (Lastest commit)

### Environment
Ubuntu 18.04, 64bit

### Reproduce
Command
```
git clone the Lastest Version firstly.
make
./ELFLoader.out poc
```

POC file at the bottom of this report.

### ASAN Report

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13007==ERROR: AddressSanitizer: SEGV on unknown address 0x623380001110 (pc 0x55aab7199870 bp 0x7ffc1737fbb0 sp 0x7ffc1737f9c0 T0)
==13007==The signal is caused by a READ memory access.
#0 0x55aab7199870 in ELFRunner src/ELFLoader.c:181
#1 0x55aab719b624 in main src/ELFLoader.c:422
#2 0x7fd64651d0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x240b2)
#3 0x55aab719656d in _start (/AFLplusplus/my_test/elfloader/tanuki/asan_bin/ELFLoader.out+0x256d)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV src/ELFLoader.c:181 in ELFRunner
==13007==ABORTING

```

### POC
[000000.zip](https://github.com/trustedsec/ELFLoader/files/9412984/000000.zip)

Any issue plz contact with me:
asteriska001@gmail.com
OR:
twitter: @Asteriska8

**Comment by freefirex** [comment]
This project was developed as a Proof of Concept in memory elf file loader.
It is not intended to correctly handle malformed object files in a safe manner.  End users are responsible for
validating that object files they create and use with this tooling will be appropriately handled on their targets.

This project is also not intended to be used by anyone other than tooling developers.  An end user would
be highly unlikely to accidentally provide unknown input to this program.

For those reasons this issue is being closed without further investigation.
